### PR TITLE
Provide installation instructions and fix a few errors

### PR DESCRIPTION
**Pull request by Jack-Bailey**
Added installation instructions
Removed duplicate links
Removed unused values in wrangler.toml
Added who.is link

### CODE REVIEW

**Comment by Jack-Bailey** [comment]
> are you sure I don't need the account id here

I'm not sure what you mean - the only thing I had to change account_id wise was setting `account_id` to mine in wrangler.toml

**Comment by alii** [comment]
When the CI runs here, I *think* it uses the account_id to deploy it to my Cloudflare account as it isn't set as an environment variable

**Comment by Jack-Bailey** [comment]
Yeah that's correct, in the guide I added it just gets the user to replace it with their own so it deploys to the user's cf account instead of trying to deploy to yours

**Comment by alii** [comment]
I see right, but if I merge this it will remove the account ID I am currently using from the wrangler.toml which is used in the CI.

**Comment by Jack-Bailey** [comment]
Does that better suit your needs? Fixes the bugs and provides a good readme on how to use it but keeps your account id so you can still use it without any reconfiguration

**Comment by alii** [comment]
For sure, that's great. Thank so so much!

**Pull request merged**
