### PR TITLE
better classification + some new sources

### PR DESCRIPTION
**Pull request by tanaybhardwaj24**
# Added:
1. rust
2. yarn
3. bandcamp
4. soundcloud

Also added comments and classified all the parameters neatly

### CODE REVIEW

**Comment by tanaybhardwaj24** [comment]
bottom text

**Review by alii — APPROVED** [review]
Great work, thank you!!!

**Comment by alii** [comment]
top text

**Comment by pxseu** [comment]
great work

**Comment by pxseu** [comment]
middle text

**Comment by alii** [comment]
caption here

**Comment by tanaybhardwaj24** [comment]
interesting title

**Pull request merged**
